sudo Rscript -e 'install.packages("evaluate", repos="https://cran.rstudio.com")'
sudo Rscript -e 'install.packages("knitr", repos="https://cran.rstudio.com")'
sudo Rscript -e 'install.packages("devtools", repos="https://cran.rstudio.com")'
sudo Rscript -e 'library(devtools);devtools::install_github("IRkernel/repr")'
sudo Rscript -e 'install.packages("htmltools", repos="https://cran.rstudio.com")'
sudo Rscript -e 'install.packages("base64enc", repos="https://cran.rstudio.com")'
sudo Rscript -e 'install.packages("opencpu", repos="https://cran.rstudio.com")'
sudo Rscript -e 'install.packages("ggplot2", repos="https://cran.rstudio.com")'
sudo Rscript -e 'install.packages("zoo", repos="https://cran.rstudio.com")'
sudo Rscript -e 'install.packages("forecast", repos="https://cran.rstudio.com")'
